RecipesAndGroceries/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
	path('RecipesManagement/',include('RecipesManagement.urls')),
    path('admin/', admin.site.urls),
]

RecipesManagement/urls.py
from django.urls import path
from . import views

app_name = 'RecipesManagement'
urlpatterns = [
    path('', views.index, name='index'),
    path('new_recipe/', views.new_recipe, name='new_recipe'),
    path('create_recipe/', views.create_recipe, name='create_recipe'),
    path('<int:recipe_id>/', views.recipe_detail, name ='detail'),
    path('<int:recipe_id>/lol/', views.link_recipe_ingredient, name ='link_recipe_ingredient'),
]

RecipesManagement/models.py
from django.db import models

class Recipe(models.Model):
	recipe_name = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date created')
	def __str__(self):
		return self.recipe_name

class Unit(models.Model):
	unit_name = models.CharField(max_length=20)
	def __str__(self):
		return self.unit_name

class Ingredient(models.Model):
	ingredient_name = models.CharField(max_length=200)
	unit = models.ForeignKey(Unit, on_delete=models.CASCADE)
	def __str__(self):
		return self.ingredient_name

class RecipeIngredient(models.Model):
	recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
	ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
	quantity = models.IntegerField(default=0)

RecipesManagement/forms.py
from django import forms

class RecipeForm(forms.Form):
	recipe_name = forms.CharField(label='Recipe name', max_length=100)

RecipesManagement/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone
#from django.template import loader

from .models import Recipe, Ingredient, Unit, RecipeIngredient
from .forms import RecipeForm


def index(request):
	recipes_list= Recipe.objects.all()
	context = {'recipes_list':recipes_list}
	return render(request, 'RecipesManagement/index.html', context) 

def new_recipe(request):
	form = RecipeForm()
	return render(request, 'RecipesManagement/new_recipe.html', {'form':form})

def create_recipe(request):
	recipe = Recipe(recipe_name=request.POST['recipe_name'], pub_date=timezone.now())
	recipe.save()
	return HttpResponseRedirect(reverse('RecipesManagement:index'))

def recipe_detail(request, recipe_id):
	recipe = get_object_or_404(Recipe, pk=recipe_id)
	return render(request, 'RecipesManagement/detail.html', {'recipe': recipe, 'ingredient_list': Ingredient.objects})

def link_recipe_ingredient(request, recipe_id):
	recipe = get_object_or_404(Recipe, pk=recipe_id)
	try:
		selected_ingredient = Ingredient.objects.get(pk=request.POST['ingredient_to_link_id'])
	except (KeyError, Ingredient.DoesNotExist):
		return render(request, 'index')
	else:
		recipe_ingredient = RecipeIngredient(recipe=recipe, ingredient=selected_ingredient)
		recipe_ingredient.save()

	return HttpResponseRedirect(reverse('RecipesManagement:detail',args=(recipe.id,)))

RecipesManagement/templates/RecipesManagement/detail.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Recipe {{ recipe.recipe_name }}</title>
	</head>
	<body>

		<h1>{{recipe.recipe_name}}</h1>

		{% for recipe_ingredient in recipe.recipeingredient_set.all %}
		<p>{{ recipe_ingredient.ingredient.ingredient_name }}</p>
		{% endfor %}
		
		{% if error_message %} <p><strong>{{ error_message }}</strong></p>{% endif %}

		<form action="{% url 'RecipesManagement:link_recipe_ingredient' recipe.id %}" method="post">
		{% csrf_token %}
			<label for="ingredient_to_link"> Ajouter un ingrédient:</label>
			<select name ="ingredient_to_link_id" id="ingredient_to_link">
		
		{% for ingredient in ingredient_list.all %}
				<option value="{{ ingredient.id }}">{{ingredient.ingredient_name}}</option>
		{% endfor %}

			</select>
		<input type="submit" value="Ajouter">
		</form>

	</body>
</html>

RecipesManagement/templates/RecipesManagement/index.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>My recipes</title>
	</head>
	<body>
	{% if recipes_list %}
		<ul>
		{% for recipe in recipes_list %}
			<li><a href="{% url 'RecipesManagement:detail' recipe.id %}">{{ recipe.recipe_name }}</a></li>
		{% endfor %}
		</ul>
	{% else %}
		<p>No recipes are available.</p>
	{% endif %}

	<form action= "{% url 'RecipesManagement:new_recipe' %}" method="get">
		<button type="Add">Add a recipe</button>
	</form>
	</body>
</html>

RecipesManagement/templates/RecipesManagement/new_recipe.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Create recipe</title>
	</head>
	<body>
		<form action="{% url 'RecipesManagement:create_recipe' %}" method="post">
		{% csrf_token %}
			{{ form }}
		<input type="submit" value="Create">
		</form>
	</body>
</html> 